services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER:
      POSTGRES_DB:
      POSTGRES_PASSWORD:
    volumes:
      - wien_talks_data:/var/lib/postgresql/data

volumes:
  wien_talks_data:
  wien_talks_test_data:
